### ISSUE TITLE
Problems with Fixed Action Button

### ISSUE THREAD

**Issue by ybendek** [MaterialPrime/material-prime#1]
I'm trying to use this library, and testing some features with Fixed Action Button an exception is throws.

I'm using PF5.3 with MyFaces2.2.8

Grave: java.lang.AbstractMethodError
    at org.primefaces.renderkit.CoreRenderer.buildAjaxRequest(CoreRenderer.java:362)
    at org.primefaces.material.component.fixedactionbutton.FixedActionButtonRenderer.renderFabItem(FixedActionButtonRenderer.java:96)
    at org.primefaces.material.component.fixedactionbutton.FixedActionButtonRenderer.encodeMarkup(FixedActionButtonRenderer.java:69)
    at org.primefaces.material.component.fixedactionbutton.FixedActionButtonRenderer.encodeEnd(FixedActionButtonRenderer.java:39)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
    at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
    at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
    at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:343)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
    at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
    at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
    at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
    at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
    at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
    at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
    at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
    at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
    at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
    at java.lang.Thread.run(Thread.java:745)

**Comment by francesco-strazzullo** [comment]
Hi ybendek, MaterialPrime it's built using PrimeFaces 5.2. I will update the dependencies right away.

**Comment by francesco-strazzullo** [comment]
Just fixed, you just need to use the last version of MaterialPrime changing the dependency like this:

```
<dependency>
    <groupId>com.github.MaterialPrime</groupId>
    <artifactId>material-prime</artifactId>
    <version>develop-SNAPSHOT</version>
</dependency>
```
